AllowedDomains:
  - apple.com.cn
  - apple.com
ExcludedDomains:
  - music.apple.com
# 并发数
Parallelism: 0
# 当设置并发数时，随机等待时间生效，该配置表示每两个请求间的最大请求时间是5秒
RandomDelayMaxTime: 5

Headers:
  User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36